# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRQeQOZG9nbpCPK8CG0n9OhJRNw0pmL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("/content/drive/MyDrive/shots_data.csv")

pd.options.mode.chained_assignment = None 
team_A = data[data["team"] == "Team A"]
team_A["dist"] = np.sqrt((team_A["x"] - 0)**2 + (team_A["y"] - 0)**2)
a_C2PT = team_A[(team_A["dist"] < 22) & (team_A["y"] <= 7.8)]
plt.scatter(a_C2PT["x"], a_C2PT["y"])
a_NC2PT = team_A[(team_A["dist"] < 23.75) & (team_A["y"] > 7.8)]
plt.scatter(a_NC2PT["x"], a_NC2PT["y"])
a_C3 = team_A[(team_A["dist"] >= 22) & (team_A["y"] <= 7.8)]
plt.scatter(a_C3["x"], a_C3["y"])
a_NC3 = team_A[(team_A["dist"] >= 23.75) & (team_A["y"] > 7.8)]
plt.scatter(a_NC3["x"], a_NC3["y"])
print("Shot Distribution of Team A:\n")


# Pie chart
a_labels = '2PT', 'C3', 'NC3'
a_2PT = len(a_C2PT) + len(a_NC2PT)
a_sizes = [((a_2PT/280) * 100), ((len(a_C3)/280)*100), ((len(a_NC3)/280)*100)]
a_explode = (0.1, 0, 0)  
a_fig1, a_ax1 = plt.subplots()
a_ax1.pie(a_sizes, explode=a_explode, labels=a_labels, autopct='%1.1f%%',
        shadow=True, startangle=90)
a_ax1.axis('equal') 

plt.show()

a_2PT_FGM = len(a_C2PT[a_C2PT["fgmade"] == 1]) + len(a_NC2PT[a_NC2PT["fgmade"] == 1])
a_2PT_three_PM = 0
a_2PT_FGA = a_2PT
a_2PT_eFG = (a_2PT_FGM + (0.5*a_2PT_three_PM))/a_2PT_FGA * 100
print("\nEffective Field goal percentage of Team A in 2PT:\n\n" + str(a_2PT_eFG) + " %")

a_C3_FGM = len(a_C3[a_C3["fgmade"] == 1])
a_C3_three_PM = a_C3_FGM
a_C3_FGA = len(a_C3)
a_C3_eFG = (a_C3_FGM + (0.5*a_C3_three_PM))/a_C3_FGA * 100
print("\nEffective Field goal percentage of Team A in C3:\n\n" + str(a_C3_eFG) + " %")

a_NC3_FGM = len(a_NC3[a_NC3["fgmade"] == 1])
a_NC3_three_PM = a_NC3_FGM
a_NC3_FGA = len(a_NC3)
a_NC3_eFG = (a_NC3_FGM + (0.5*a_NC3_three_PM))/a_NC3_FGA * 100
print("\nEffective Field goal percentage of Team A in NC3:\n\n" + str(a_NC3_eFG) + " %")

team_B = data[data["team"] == "Team B"]
team_B["dist"] = np.sqrt((team_B["x"] - 0)**2 + (team_B["y"] - 0)**2)
b_C2PT = team_B[(team_B["dist"] < 22) & (team_B["y"] <= 7.8)]
plt.scatter(b_C2PT["x"], b_C2PT["y"])
b_NC2PT = team_B[(team_B["dist"] < 23.75) & (team_B["y"] > 7.8)]
plt.scatter(b_NC2PT["x"], b_NC2PT["y"])
b_C3 = team_B[(team_B["dist"] >= 22) & (team_B["y"] <= 7.8)]
plt.scatter(b_C3["x"], b_C3["y"])
b_NC3 = team_B[(team_B["dist"] >= 23.75) & (team_B["y"] > 7.8)]
plt.scatter(b_NC3["x"], b_NC3["y"])
print("Shot Distribution of Team B:\n")

# Pie chart
b_labels = '2PT', 'C3', 'NC3'
b_2PT = len(b_C2PT) + len(b_NC2PT)
b_sizes = [((b_2PT/280) * 100), ((len(b_C3)/280)*100), ((len(b_NC3)/280)*100)]
b_explode = (0.1, 0, 0)  

b_fig1, b_ax1 = plt.subplots()
b_ax1.pie(b_sizes, explode=b_explode, labels=b_labels, autopct='%1.1f%%',
        shadow=True, startangle=90)
b_ax1.axis('equal') 

plt.show()

b_2PT_FGM = len(b_C2PT[b_C2PT["fgmade"] == 1]) + len(b_NC2PT[b_NC2PT["fgmade"] == 1])
b_2PT_three_PM = 0
b_2PT_FGA = b_2PT
b_2PT_eFG = (b_2PT_FGM + (0.5*b_2PT_three_PM))/b_2PT_FGA * 100
print("\nEffective Field goal percentage of Team B in 2PT:\n\n" + str(b_2PT_eFG) + " %")

b_C3_FGM = len(b_C3[b_C3["fgmade"] == 1])
b_C3_three_PM = b_C3_FGM
b_C3_FGA = len(b_C3)
b_C3_eFG = (b_C3_FGM + (0.5*b_C3_three_PM))/b_C3_FGA * 100
print("\nEffective Field goal percentage of Team B in C3:\n\n" + str(b_C3_eFG) + " %")

b_NC3_FGM = len(b_NC3[b_NC3["fgmade"] == 1])
b_NC3_three_PM = b_NC3_FGM
b_NC3_FGA = len(b_NC3)
b_NC3_eFG = (b_NC3_FGM + (0.5*b_NC3_three_PM))/b_NC3_FGA * 100
print("\nEffective Field goal percentage of Team B in NC3:\n\n" + str(b_NC3_eFG) + " %")
